// Default portal content. Loaded into the database on first run, then fully
// editable from the admin UI. Edit here only if you want to change the defaults.

export const seed = {
  project: {
    name: 'Multi-Merchant Payment Platform — V1',
    tagline: 'WooCommerce + Stripe Connect · Custom platform build',
    client: 'Michael Billy Ravoy',
    builder: 'Simone Benedict Celestial',
    startDate: '2026-06-29',
    endDate: '2026-09-20',
    stack: 'WordPress / WooCommerce + Stripe Connect',
    status: 'In progress — Week 1 (Setup)',
  },

  announcement:
    'Welcome to the project portal. Week 1 is intentionally light — setup, access, and alignment. Please complete the items in “What We Need From You,” confirm the open decisions in “Open Questions,” and use Chat anytime. — Simone',

  // --- 12-week interactive timeline (Mon Jun 29 2026 → Sep 20 2026) ---
  timeline: [
    {
      id: 'w1',
      week: 1,
      title: 'Kickoff & Setup',
      dates: 'Jun 29 – Jul 5',
      light: true,
      status: 'in_progress',
      focus: 'Light week — alignment, access, and tooling. No heavy development yet.',
      tasks: [
        { id: 'w1t1', label: 'Kickoff call + confirm scope and goals', done: false },
        { id: 'w1t2', label: 'Set up Jira board, GitHub repo, and Slack channel', done: false },
        { id: 'w1t3', label: 'Collect access: WordPress, hosting, Stripe', done: false },
        { id: 'w1t4', label: 'Confirm fund-flow model (platform receives funds first — separate charges & transfers)', done: false },
        { id: 'w1t5', label: 'Walk through the kickoff checklist together', done: false },
      ],
      clientNeeds: ['Stripe + WordPress access', 'Confirm main & technical contacts', 'Sign-off to begin'],
    },
    {
      id: 'w2',
      week: 2,
      title: 'Architecture & Foundations',
      dates: 'Jul 6 – Jul 12',
      status: 'not_started',
      focus: 'Final architecture, database design, and Stripe Connect configuration. (Checkpoint 1)',
      tasks: [
        { id: 'w2t1', label: 'Finalize system architecture & core data model', done: false },
        { id: 'w2t2', label: 'Configure Stripe Connect in test mode', done: false },
        { id: 'w2t3', label: 'Design database schema (merchants, transactions, payouts, etc.)', done: false },
        { id: 'w2t4', label: 'Implementation plan sign-off — Checkpoint 1', done: false },
      ],
      clientNeeds: ['Approve architecture (Checkpoint 1)', 'Confirm commission model & rate'],
    },
    {
      id: 'w3',
      week: 3,
      title: 'Merchant Model & Onboarding (start)',
      dates: 'Jul 13 – Jul 19',
      status: 'not_started',
      focus: 'Merchant records, connected-account mapping, and the start of Stripe onboarding.',
      tasks: [
        { id: 'w3t1', label: 'Build merchant records + Stripe connected-account mapping', done: false },
        { id: 'w3t2', label: 'Start Stripe Connect onboarding flow (Express + hosted)', done: false },
        { id: 'w3t3', label: 'Enable the transfers capability on connected accounts', done: false },
        { id: 'w3t4', label: 'Begin onboarding status tracking', done: false },
      ],
      clientNeeds: [],
    },
    {
      id: 'w4',
      week: 4,
      title: 'Onboarding + Gateway Scaffolding',
      dates: 'Jul 20 – Jul 26',
      status: 'not_started',
      focus: 'Finish onboarding tracking and scaffold the WooCommerce payment gateway plugin.',
      tasks: [
        { id: 'w4t1', label: 'Complete onboarding status tracking', done: false },
        { id: 'w4t2', label: 'Guardrail: block live payments until merchant is payout-ready', done: false },
        { id: 'w4t3', label: 'Scaffold custom WooCommerce payment gateway plugin', done: false },
      ],
      clientNeeds: ['Provide 1–2 test merchants for onboarding'],
    },
    {
      id: 'w5',
      week: 5,
      title: 'WooCommerce Gateway Plugin',
      dates: 'Jul 27 – Aug 2',
      status: 'not_started',
      focus: 'Build the custom checkout path through Stripe.',
      tasks: [
        { id: 'w5t1', label: 'Register custom WooCommerce payment method', done: false },
        { id: 'w5t2', label: 'Read order amount, currency, customer & merchant ownership', done: false },
        { id: 'w5t3', label: 'Create Stripe payment session (hosted / Stripe-secured)', done: false },
        { id: 'w5t4', label: 'Store Stripe references on the WooCommerce order', done: false },
      ],
      clientNeeds: [],
    },
    {
      id: 'w6',
      week: 6,
      title: 'Checkout Flow + Onboarding Wrap',
      dates: 'Aug 3 – Aug 9',
      status: 'not_started',
      focus: 'End-to-end test checkout and finalize onboarding. (Checkpoints 2 & 3)',
      tasks: [
        { id: 'w6t1', label: 'Test full checkout flow in Stripe test mode', done: false },
        { id: 'w6t2', label: 'Handle success / cancel / failed payment states', done: false },
        { id: 'w6t3', label: 'Finalize merchant onboarding — Checkpoints 2 & 3', done: false },
      ],
      clientNeeds: ['Provide sample products/orders for testing'],
    },
    {
      id: 'w7',
      week: 7,
      title: 'Platform Fee & Transfers Logic',
      dates: 'Aug 10 – Aug 16',
      status: 'not_started',
      focus: 'Commission engine and the separate charges & transfers fund flow.',
      tasks: [
        { id: 'w7t1', label: 'Commission calculation engine (per-transaction platform fee)', done: false },
        { id: 'w7t2', label: 'Separate charges & transfers implementation', done: false },
        { id: 'w7t3', label: 'Wire transfer_group + source_transaction (avoid negative balance)', done: false },
        { id: 'w7t4', label: 'Stripe-fee handling (deduct from merchant) + store-credit math', done: false },
      ],
      clientNeeds: [],
    },
    {
      id: 'w8',
      week: 8,
      title: 'Webhooks & Transaction Records',
      dates: 'Aug 17 – Aug 23',
      status: 'not_started',
      focus: 'Reliable webhook processing and order/record updates. (Checkpoint 4)',
      tasks: [
        { id: 'w8t1', label: 'Stripe webhook endpoint + signature verification', done: false },
        { id: 'w8t2', label: 'Idempotency: store event IDs to prevent duplicates', done: false },
        { id: 'w8t3', label: 'Write transaction records (gross, fee, net, status)', done: false },
        { id: 'w8t4', label: 'Update WooCommerce order status — Checkpoint 4', done: false },
      ],
      clientNeeds: [],
    },
    {
      id: 'w9',
      week: 9,
      title: 'Internal Admin Dashboard',
      dates: 'Aug 24 – Aug 30',
      status: 'not_started',
      focus: 'Central platform view of merchants, payments, fees, and payouts.',
      tasks: [
        { id: 'w9t1', label: 'Merchants list + merchant detail page', done: false },
        { id: 'w9t2', label: 'Platform-wide transactions (gross / fees / net / payout)', done: false },
        { id: 'w9t3', label: 'Filters by merchant, date, status + CSV export', done: false },
      ],
      clientNeeds: [],
    },
    {
      id: 'w10',
      week: 10,
      title: 'Merchant Dashboard',
      dates: 'Aug 31 – Sep 6',
      status: 'not_started',
      focus: 'Merchant-scoped dashboard with strict data isolation. (Checkpoint 5)',
      tasks: [
        { id: 'w10t1', label: 'Merchant login + data scoping', done: false },
        { id: 'w10t2', label: 'Own transactions, fees, estimated net, payout status', done: false },
        { id: 'w10t3', label: 'CSV export + merchant isolation tests — Checkpoint 5', done: false },
      ],
      clientNeeds: ['Branding assets: logo, colors, platform name, support email'],
    },
    {
      id: 'w11',
      week: 11,
      title: 'Testing & QA',
      dates: 'Sep 7 – Sep 13',
      status: 'not_started',
      focus: 'Hardening: payments, webhooks, isolation, reporting.',
      tasks: [
        { id: 'w11t1', label: 'Payment success / fail / incomplete tests', done: false },
        { id: 'w11t2', label: 'Webhook retries + duplicate prevention', done: false },
        { id: 'w11t3', label: 'Merchant isolation + commission accuracy', done: false },
        { id: 'w11t4', label: 'Reports/exports, store credits, dispute visibility', done: false },
      ],
      clientNeeds: [],
    },
    {
      id: 'w12',
      week: 12,
      title: 'Deployment & Handoff',
      dates: 'Sep 14 – Sep 20',
      status: 'not_started',
      focus: 'Go live and hand over. (Checkpoint 6 — final)',
      tasks: [
        { id: 'w12t1', label: 'Production deploy + live keys + webhook endpoint', done: false },
        { id: 'w12t2', label: 'Production smoke tests', done: false },
        { id: 'w12t3', label: 'Handoff docs + admin & merchant guides', done: false },
        { id: 'w12t4', label: 'Known limitations + V2 roadmap — Checkpoint 6', done: false },
      ],
      clientNeeds: ['Confirm go-live window', 'Decide on $500/mo support retainer'],
    },
  ],

  // --- What We Need From You (from the kickoff checklist) ---
  actionItems: [
    { id: 'a1', category: 'Contract & Payment', label: 'Signed agreement', detail: 'Signed contract / SOW from both parties', neededBy: 'Before kickoff', status: 'Provided' },
    { id: 'a2', category: 'Contract & Payment', label: 'Downpayment', detail: 'USD $500 downpayment confirmation', neededBy: 'Before kickoff', status: 'In Progress' },
    { id: 'a3', category: 'Project Access', label: 'WordPress / WooCommerce access', detail: 'Admin login or invited user access', neededBy: 'Before development', status: 'Not Started' },
    { id: 'a4', category: 'Project Access', label: 'Hosting / server access', detail: 'Hosting panel, SFTP, or deployment access', neededBy: 'Before development', status: 'Not Started' },
    { id: 'a5', category: 'Project Access', label: 'Domain / DNS access', detail: 'For webhook, SSL, or subdomain setup if needed', neededBy: 'Before testing', status: 'Not Started' },
    { id: 'a6', category: 'Payment Account', label: 'Stripe access', detail: 'Stripe account access or developer invite', neededBy: 'Before development', status: 'Not Started' },
    { id: 'a7', category: 'Payment Account', label: 'Stripe Connect confirmation', detail: 'Confirm Stripe Connect can be used for the platform', neededBy: 'Before development', status: 'Not Started' },
    { id: 'a8', category: 'Website Setup', label: 'Current WooCommerce setup details', detail: 'Current site, payment plugins, and checkout setup', neededBy: 'Before development', status: 'Not Started' },
    { id: 'a9', category: 'Website Setup', label: 'Staging or backup plan', detail: 'Confirm staging site or backup/rollback process', neededBy: 'Before development', status: 'Not Started' },
    { id: 'a10', category: 'Business Rules', label: 'Platform fee rules', detail: 'Commission percentage or fee structure per transaction', neededBy: 'Before development', status: 'Not Started' },
    { id: 'a11', category: 'Business Rules', label: 'Merchant onboarding rules', detail: 'How merchants are added, approved, and activated', neededBy: 'Before development', status: 'Not Started' },
    { id: 'a12', category: 'Business Rules', label: 'Refund / store credit rules', detail: 'Store credit process and whether card refunds are allowed', neededBy: 'Before testing', status: 'Not Started' },
    { id: 'a13', category: 'Branding & Content', label: 'Brand assets', detail: 'Logo, brand colors, platform name, support email', neededBy: 'Before dashboard build', status: 'Not Started' },
    { id: 'a14', category: 'Test Data', label: 'Test merchants', detail: '1–2 sample merchants for onboarding & dashboard testing', neededBy: 'Before testing', status: 'Not Started' },
    { id: 'a15', category: 'Test Data', label: 'Sample products / orders', detail: 'Sample WooCommerce products/orders for payment testing', neededBy: 'Before testing', status: 'Not Started' },
    { id: 'a16', category: 'Communication', label: 'Main project contact', detail: 'Primary person for decisions and approvals', neededBy: 'Before kickoff', status: 'Not Started' },
    { id: 'a17', category: 'Communication', label: 'Technical contact', detail: 'Person who can help with access, hosting, site, or Stripe', neededBy: 'Before kickoff', status: 'Not Started' },
    { id: 'a18', category: 'Support Setup', label: 'Post-launch support decision', detail: 'Confirm whether the $500/month retainer will be activated', neededBy: 'Before launch', status: 'Not Started' },
  ],

  // --- Open Questions / decisions ---
  questions: [
    { id: 'q1', text: 'Fund flow + Stripe fee: confirm the platform receives all funds first, then pays merchants (separate charges & transfers). Recommended: deduct the Stripe fee (2.9% + $0.30) from each merchant transfer so you keep your full commission. Approve?', context: 'This maximizes your revenue and is the standard marketplace model.', answer: '', status: 'open' },
    { id: 'q2', text: 'Commission model: flat %, fixed amount, or mixed — and what rate? (e.g., 5% per transaction)', context: 'Drives the fee engine and dashboards.', answer: '', status: 'open' },
    { id: 'q3', text: 'Site structure: one WooCommerce instance with multiple merchants, or separate WooCommerce sites per merchant?', context: 'Affects architecture and scope.', answer: '', status: 'open' },
    { id: 'q4', text: 'Connected account type: Stripe Express (recommended — hosted onboarding, low effort) or Custom (more control, more work)?', context: '', answer: '', status: 'open' },
    { id: 'q5', text: 'Transfer timing: pay merchants immediately per sale, or hold X days as refund/dispute protection?', context: 'Reduces negative-balance / clawback risk.', answer: '', status: 'open' },
    { id: 'q6', text: 'Refunds: store credit only, or also allow card refunds in some cases?', context: 'You preferred store credits; some cases may still need card refunds.', answer: '', status: 'open' },
    { id: 'q7', text: 'Statement descriptor: what name should appear on customers’ card statements? (The platform is merchant of record.)', context: '', answer: '', status: 'open' },
    { id: 'q8', text: 'Branding: logo, brand colors, platform name, and support email for the dashboards?', context: 'Needed before the dashboard build (Week 9–10).', answer: '', status: 'open' },
  ],

  // --- Documents & accounts ---
  documents: [
    { id: 'd1', name: 'V1 Proposal', type: 'Proposal', note: 'Full technical plan, scope, pricing', url: '' },
    { id: 'd2', name: 'Software Development Agreement (V2)', type: 'Contract', note: 'Signed via Zoho Sign', url: '' },
    { id: 'd3', name: 'Discovery Questions & Answers', type: 'Discovery', note: 'Confirmed requirements', url: '' },
    { id: 'd4', name: 'Kickoff Checklist', type: 'Checklist', note: 'What we need from you', url: '' },
    { id: 'd5', name: 'Invoice INV-2026-0623-001 (Revised)', type: 'Invoice', note: '$500 downpayment', url: '' },
  ],

  // --- Accounts (admin-managed; mark adminOnly to hide from the client) ---
  accounts: [
    { id: 'ac1', label: 'Stripe (Platform)', category: 'Payments', url: 'https://dashboard.stripe.com', details: 'Account email: (to fill)\nMode: Test → Live\nStripe Connect: to be enabled', adminOnly: false },
    { id: 'ac2', label: 'WordPress / WooCommerce', category: 'Website', url: '', details: 'Admin URL: (to fill)\nUsername: (to fill)', adminOnly: false },
    { id: 'ac3', label: 'Hosting', category: 'Infrastructure', url: '', details: 'Provider: (to fill)\nControl panel: (to fill)', adminOnly: false },
    { id: 'ac4', label: 'GitHub', category: 'Code', url: '', details: 'Repository: (to fill)', adminOnly: false },
    { id: 'ac5', label: 'Payment / Remittance', category: 'Billing', url: '', details: 'Where to send invoice payments (e.g. Wise / Maya). Fill in as needed.', adminOnly: false },
  ],

  // --- Quick links (admin-editable) ---
  links: [
    { id: 'l1', label: 'GitHub Repo', url: '', icon: 'code', note: 'Source code & version control' },
    { id: 'l2', label: 'Jira Board', url: '', icon: 'board', note: 'Task tracking' },
    { id: 'l3', label: 'Slack Channel', url: '', icon: 'chat', note: 'Day-to-day communication' },
    { id: 'l4', label: 'Stripe Dashboard', url: 'https://dashboard.stripe.com', icon: 'card', note: 'Payments & Connect' },
    { id: 'l5', label: 'Staging Site', url: '', icon: 'globe', note: 'Preview environment' },
  ],

  // --- Payment milestones ($2,000 total) ---
  payments: [
    { id: 'p1', label: '25% downpayment to start', amount: 500, paid: false },
    { id: 'p2', label: 'Architecture + Stripe Connect setup', amount: 250, paid: false },
    { id: 'p3', label: 'Merchant onboarding', amount: 250, paid: false },
    { id: 'p4', label: 'WooCommerce checkout + platform fee', amount: 350, paid: false },
    { id: 'p5', label: 'Webhook handling + transaction records', amount: 250, paid: false },
    { id: 'p6', label: 'Dashboards / reporting', amount: 250, paid: false },
    { id: 'p7', label: 'Final testing, deployment & handoff', amount: 150, paid: false },
  ],
};
